experiment:
  description: ${model.name} ${model.size} ${experiment.instruct_status} ${experiment.exp_name}
  exp_name: InBatch
  instruct_status: Instruct
  path_suffix: ${model.short_name}/${model.size}/${experiment.instruct_status}/${experiment.exp_name}/
index_config:
  cand_pools_config:
    cand_pools_name_to_idx:
    - edis_task2
    - nights_task4
    - fashioniq_task7
    - cirr_task7
    - UNION
    enable_idx: true
  embed_dir_name: embed
  faiss_config:
    dim: 2048
    idx_type: Flat
    metric: METRIC_INNER_PRODUCT
  index_dir_name: indices
mbeir_data_dir: /data/M-BEIR/sub_MBEIR
model:
  name: JinaV4UniIR
  pretrained_model_dir: /data/LR1/src/models/jina_v4oauxa/jina_v4oauxa
  short_name: JinaV4
  size: Large
uniir_dir: /data/LR1
