#!/usr/bin/env python3
"""
验证Stage-2训练时checkpoint的保存和加载逻辑
"""

print("=" * 80)
print("Stage-2 训练权重保存/加载逻辑验证")
print("=" * 80)

print("\n【1. 权重冻结逻辑 - freeze_all_except_hard_gate()】")
print("位置: train.py:131-209")
print("逻辑:")
print("  1. 先冻结所有参数: param.requires_grad = False")
print("  2. 解冻hard_gate参数: gate_module.parameters() -> requires_grad = True")
print("  3. 解冻LoRA参数: 'lora_' in name -> requires_grad = True")
print("  4. 解冻embedding映射层: multi_vector_projector -> requires_grad = True")
print("  5. 解冻thought token embeddings (通过grad hook)")
print()
print("✓ 结论: Stage-2会正确设置requires_grad=True for hard_gate")

print("\n【2. 权重保存逻辑 - save_checkpoint()】")
print("位置: train.py:374-420")
print("关键代码 (第393-395行):")
print("  adapter_state_dict = {}")
print("  for name, param in model_to_save.named_parameters():")
print("      if param.requires_grad:  # 只保存trainable参数")
print("          adapter_state_dict[name] = param.data.cpu()")
print()
print("保存的参数包括:")
print("  - LoRA参数: base_model.model.*.lora_A/lora_B")
print("  - hard_gate参数: base_model.model.step_predictor_gate.* 或 hard_gate.*")
print("  - embedding映射: base_model.model.multi_vector_projector.*")
print("  - thought embeddings: base_model.model.model.language_model.embed_tokens.weight")
print()
print("✓ 结论: 所有requires_grad=True的参数都会被保存")

print("\n【3. 权重加载逻辑 - load_lora_checkpoint()】")
print("位置: train.py:442-506")
print("关键代码 (第471-473行):")
print("  for name, param in adapter_state_dict.items():")
print("      if name in model_state_dict:")
print("          model_state_dict[name].copy_(param)")
print()
print("✓ 结论: checkpoint中的所有参数都会被加载回模型")

print("\n【4. 潜在问题检查】")
print()
print("问题1: hard_gate是否在保存前被正确初始化?")
print("  - 检查: train.py:724-727")
print("  - 代码: base_model_for_config.setup_hard_gate(...)")
print("  - 时机: 在freeze_all_except_hard_gate()之前调用")
print("  ✓ 正确: hard_gate在冻结前已初始化")
print()
print("问题2: 保存时hard_gate的参数名是什么?")
print("  - 可能的名称:")
print("    * base_model.model.step_predictor_gate.mlp.0.weight")
print("    * base_model.model.step_predictor_gate.mlp.0.bias")
print("    * base_model.model.step_predictor_gate.mlp.2.weight")
print("    * base_model.model.step_predictor_gate.mlp.2.bias")
print("    * 或 base_model.model.hard_gate.* (向后兼容)")
print("  ✓ 只要requires_grad=True，就会被保存")
print()
print("问题3: 加载时是否会跳过hard_gate参数?")
print("  - 检查: load_lora_checkpoint不会过滤参数名")
print("  - 只要name in model_state_dict，就会加载")
print("  ✓ 不会跳过")
print()
print("问题4: Stage-2 resume训练时是否会重新初始化hard_gate?")
print("  - 检查: train.py:766-771 (resume逻辑)")
print("  - 代码: model, checkpoint = load_lora_checkpoint(model, checkpoint_path)")
print("  - 然后: train.py:724-727 会再次调用 setup_hard_gate()")
print("  ⚠️  潜在问题: setup_hard_gate()可能会重新初始化权重!")

print("\n【5. 发现的问题】")
print()
print("⚠️  CRITICAL: 可能存在权重覆盖问题!")
print()
print("执行顺序:")
print("  1. 加载模型: JinaEmbeddingsV4Model.from_pretrained()")
print("  2. [如果resume] 加载checkpoint: load_lora_checkpoint() -> 加载hard_gate权重")
print("  3. 初始化hard_gate: setup_hard_gate() -> 可能重新初始化权重!")
print("  4. 冻结参数: freeze_all_except_hard_gate()")
print()
print("如果setup_hard_gate()会重新初始化权重，那么第2步加载的权重会被覆盖!")

print("\n【6. 建议的修复方案】")
print()
print("方案1: 修改setup_hard_gate()，如果gate已存在则跳过初始化")
print("方案2: 调整执行顺序，在load_checkpoint之前调用setup_hard_gate()")
print("方案3: 在load_checkpoint之后检查是否需要setup_hard_gate()")
print()
print("推荐: 方案1 - 让setup_hard_gate()变成幂等操作")

print("\n" + "=" * 80)
print("验证完成")
print("=" * 80)
